/**:
  ydlidar_ros2_driver_node:
    ros__parameters:
      port: /dev/ttyUSB0
      frame_id: r1/laser_frame
      ignore_array: ""
      baudrate: 230400
      lidar_type: 1
      device_type: 0
      sample_rate: 3
      intensity_bit: 8
      abnormal_check_count: 4
      fixed_resolution: true
      reversion: false
      inverted: true
      auto_reconnect: true
      isSingleChannel: false
      intensity: true
      support_motor_dtr: false
      angle_max: 180.0
      angle_min: -180.0
      range_max: 10.0
      range_min: 0.15
      frequency: 6.0
      invalid_range_is_inf: false
